layout_spectrum: 0.3220360509585589
typography_spectrum: 0.07637955574318767
color:
  saturation: 0.31481769727542996
  brandStrength: 0.8856169995851815
  rhythmicContrast: 0.06126769678667188
  brandColors:
    - '#FF6138'
    - '#FFFF9D'
    - '#BEEB9F'
    - '#79BD8F'
    - '#00A388'
  lightness: 0.522532545728609
author:
  email: lv_hakola@yahoo.com
  name: Levi Hakola
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
navigation:
  - name: YouTube
    url: 'https://www.youtube.com/channel/UCKcxuih3-5Ga9vdwPTjyf-Q'
    type: external
  - name: About Us
    id: 27c8fc9d-ae6b-47fe-bad9-4edb0c2b20c8
    type: content
name: Big Island Treehouse
