typography_spectrum: 0.07186292670667171
color:
  saturation: 0.13252217881381512
  brandStrength: 0.7626769372727722
  rhythmicContrast: 0.3802798914257437
  brandColors:
    - '#00261C'
    - '#044D29'
    - '#168039'
    - '#45BF55'
    - '#96ED89'
  lightness: 0.9931265185587108
layout_spectrum: 0.38574837846681476
author:
  email: lv_hakola@yahoo.com
  name: Levi Hakola
name: Big Island Treehouse
navigation:
  - name: YouTube
    url: 'https://www.youtube.com/channel/UCKcxuih3-5Ga9vdwPTjyf-Q'
    type: external
  - name: About Us
    id: 27c8fc9d-ae6b-47fe-bad9-4edb0c2b20c8
    type: content
  - name: Instagram
    url: 'https://www.instagram.com/bigtinytreehouse/'
    type: external
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
