author:
  email: lv_hakola@yahoo.com
  name: Levi Hakola
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 1
  brandStrength: 1
  lightness: 0.5595745
  brandColors:
    - '#FFFFDB'
    - '#011831'
    - '#FEC9BD'
    - '#147F73'
    - '#D68284'
  rhythmicContrast: 0.4148936
typography_spectrum: 0.3297872
navigation:
  - name: YouTube
    url: 'https://www.youtube.com/channel/UCKcxuih3-5Ga9vdwPTjyf-Q'
    type: external
  - name: About Us
    id: 27c8fc9d-ae6b-47fe-bad9-4edb0c2b20c8
    type: content
layout_spectrum: 0.1744681
name: Big Island Treehouse
